name: CPSChecker
version: 1.0.0
main: net.muffinized.cpschecker.CPSChecker
api-version: 1.20
author: Larssies
load: STARTUP
commands:
  cpschecker:
    description: Reload the config
    usage: /cpschecker reload
    permission: cpschecker.reload
    aliases: [cps]